### ISSUE TITLE
`torch` seems to be required but not installed

### ISSUE THREAD

**Issue by dtch1997** [steering-vectors/steering-vectors#15]
To reproduce: 
```bash
pdm install
python -m steering_vectors
```

Error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/daniel/steering-vectors/steering_vectors/__init__.py", line 3, in <module>
    from .layer_matching import (
  File "/home/daniel/steering-vectors/steering_vectors/layer_matching.py", line 5, in <module>
    from torch import nn
ModuleNotFoundError: No module named 'torch'
```

**Comment by chanind** [comment]
This is semi-intentional. We can't easily add torch as a main dependency of the project, since how you install torch depends on your machine and stuff (e.g. the cuda version vs CPU version), so it seems easiest to just let the user figure out how to get torch installed. We depend on huggingface which also depends on torch, but they also don't seem to directly try to install it as part of the package I think for the same reason.  We have torch in the dev dependencies so it should be fine for us in development / in CI.

Maybe we could check if torch exists when loading the main `__init__.py` and give a more useful error message instructing the user to install torch if it's not installed already at that point?
